### ISSUE TITLE
技術・環境の選定

### ISSUE THREAD

**Issue by shunyokota** [shunyokota/nadukete#1]
言語：ruby 2.4.1（たぶん今最新）
FW：Ruby on Rails 5.1.5
DB：MySQL or MariaDB（たぶんどっちもそんな変わらないのでないか）
仮想環境とか作りましょうか？
・vagrant -- 使ったことあります
・Docker -- よく分からない

仮想環境使うと、どちらかが環境を作ってそれをそのまま渡す、みたいなことが出来るはず。

あと決めないといけないことがあれば決めましょう

**Comment by BintaPlanning** [comment]
vagrant 使ったことないので学習するところからになっちゃいますね。。
軽くググったところDocker使うにしてもvagrant が必要になる場面が多いみたいですね。
私の開発マシンはLinuxなのでDockerを直接扱えるみたいですが、横田さんがやったことあるのならvagrantで環境を統一しましょうか。

**Comment by BintaPlanning** [comment]
あと決めることは本番環境をクラウドにするかVPSにするか。
クラウドにするならAWSかHerokuか、VPSにするならどこかってところでしょうか。

**Comment by BintaPlanning** [comment]
vagrantなんとなくわかってきました。
横田さんって今の開発環境って自分のmacにvirtual box入れてvagrantで他の人と同じ環境にしてる感じですか？

**Comment by shunyokota** [comment]
そうです！
vagrantは環境統一するのに使った方がよさそうですね。
サーバーはVPSでいいんじゃないですか。
AWSは高すぎるし、Herokuは学習目的だと楽しすぎるし。
しんどくなってきて楽したくなったら、HerokuのHobby（$7/Dyno/月）もありかもしれないですが。

**Comment by BintaPlanning** [comment]
Docker使うとさらに良さそうですけど、最小構成でとりあえず行きましょう。

VPSはどこがいいですかね？Conohaやさくらは二郎データベースで検討しました。

**Comment by shunyokota** [comment]
http://www.server-memo.net/vps/sakura_conoha.html#VPSConoHa-2
情報もう古いのは微妙ですけど、これ見る限りだとConohaが良さそうな気はします。
信頼と安定とか、今の僕らのレベルならどうでもいいと思いますし。

**Comment by BintaPlanning** [comment]
質問箱を作ったせせりさんもConohaなのでConohaにしましょう。

本番環境はある程度ローカルで開発してから用意します？それとも最初から本番運用を想定して用意しときますか？

**Comment by shunyokota** [comment]
後からでいいんじゃないですかね。
お金もったいないですし。

**Comment by BintaPlanning** [comment]
了解しました。
ではある程度作ってからということで。
